
select * from "WR_FIVETRAN_DB"."ADWORDS_FIVETRAN_STG"."CAMPAIGN_STATS" limit 100

 "WR_FIVETRAN_DB"."ADWORDS_FIVETRAN_STG"."CAMPAIGN_STATS" -- OK
"WR_FIVETRAN_DB"."ADWORDS_FIVETRAN_STG"."KEYWORD_STATS -- empty
